import {
  annotatedAnalyzerOutput,
  incompleteAnalyzerOutput,
  measuredCoverage,
  type Analyzer,
  type AnalyzerFinding,
} from './types'
import { classifyLines, commentSyntaxFor, contentWords, dataBlockIds, type ClassifiedLine } from './comments'
import { stripStringLiterals } from './support'

/**
 * `looksGenerated` reads five lines, and codegen that leads with an
 * eslint-disable banner declares itself lower down. Comment-shape rules are the
 * most sensitive to that gap — a generated route tree measured as a redundant
 * comment hit — so they check a wider window locally rather than widening the
 * shared helper, which feeds LOC totals and every other analyzer.
 */
const GENERATED_WINDOW = 30
const GENERATED_DECLARATION =
  /auto-?generated|@generated|generated by|do not edit|this file (?:was|is) automatically generated/i

/** Paths whose comments were written by a scaffolder, not by the author. */
const SCAFFOLD_PATH = [
  /(?:^|\/)(?:migrations|alembic|versions|_generated|\.storybook)\//,
  /\.config\.[^/]+$/,
  /(?:^|\/)env\.py$/,
  /\.gen\.[jt]sx?$/,
  /_pb\.[jt]s$/,
  /\.pb\.go$/,
]

const LICENCE_HEADER = /Copyright|SPDX-License|Licensed under|Apache License|MIT License/i
const LICENCE_WINDOW_BYTES = 1200

/** A file needs enough code for its comment ratio to mean anything. */
const MIN_CODE_LINES = 25
/**
 * Density floor. Five of eight measured repositories have a comment-to-code
 * median of exactly 0.000, where `3 x median` would make every commented file
 * an outlier. The floor is what stops that, not a tuning knob.
 */
const DENSITY_FLOOR = 0.25
const DENSITY_MULTIPLE = 3
const DENSITY_MIN_COMMENTS = 12

const REDUNDANT_FILE_THRESHOLD = 3
const REDUNDANT_LOW_THRESHOLD = 5
const NARRATION_FILE_THRESHOLD = 2
const NARRATION_LOW_THRESHOLD = 4

const MAX_COMMENT_CHARS = 90
const OVERLAP_RATIO = 0.6

/** Tool pragmas and tracker markers are instructions, not commentary. */
const DIRECTIVE =
  /^(?:(?:TODO|FIXME|HACK|XXX|NOTE|eslint|prettier|biome|noqa|c8|istanbul|nosec|pylint|ruff|Deprecated)\b|@ts-|type:)/i
const BANNER = /^[-=*#\s]+$/

/**
 * A comment naming the thing declared beneath it is a section label, not a
 * restatement — `// Delete API Key` above `const deleteApiKey = …` is how the
 * ecosystem writes headings. With the explanatory-marker test below, this
 * suppresses 25%-78% of naive matches and is what takes a heavily documented
 * codebase to zero.
 */
const DECLARATION = new RegExp([
  String.raw`^(?:(?:export|default|public|private|protected|static|async|abstract|declare|pub|final)\s+)*(?:function|class|interface|type|enum|struct|impl|trait|def|func|fn|const|let|var|val)\b`,
  String.raw`^(?:export\s+)?(?:const|let|var)\s+\w+\s*[:=]\s*(?:async\s*)?(?:\([^)]*\)|\w+)\s*(?::[^=]*)?=>`,
  String.raw`^\w+\s*[:(]\s*(?:async\s*)?(?:function|\()`,
  // A class or object method signature opening its body. `async createConnection(
  // params: any) {` is the same section-label shape as a named function, and the
  // control-flow lookahead keeps `if (…) {` reportable.
  String.raw`^(?!(?:if|for|while|switch|catch|do|else|return|match|with|using|try|foreach|unless|elif)\b)(?:(?:public|private|protected|static|async|abstract|override|get|set)\s+)*[\w$]+\s*(?:<[^>]*>)?\s*\([^)]*\)\s*(?::\s*[^{]*)?\{$`,
  String.raw`^@\w+`,
  // An object-literal key opening a block is a pseudo-declaration; treating it
  // as code removed a measured false positive.
  String.raw`^['"]?[\w$-]+['"]?\s*:\s*\{`,
].join('|'))

/** A comment that says why is doing its job, whatever words it shares with the code. */
const EXPLANATORY =
  /\b(?:because|so that|since|otherwise|avoid|must|cannot|only|instead|note|caution|workaround|bug|see)\b|https?:/i

/**
 * String and regex literals, blanked.
 *
 * A comment whose only overlap with the line below it is the CONTENT of a
 * literal is naming the datum, not restating the statement. Measured on this
 * codebase: `// C# Process.Start` above `if (m === 'start' && /process/.test(…))`
 * is a language label on one branch of a dispatch table, and the words it
 * shares are the strings being matched. Every measured true positive shares at
 * least one word with an identifier, so requiring that costs no recall.
 */
const REGEX_LITERAL = /\/(?:\\.|\[[^\]]*\]|[^/\n\\])+\/[gimsuy]*/g

function withoutLiterals(code: string): string {
  return stripStringLiterals(code, ' ').replace(REGEX_LITERAL, ' ')
}

/**
 * Comment shapes that describe the edit, the reader, or the author's opinion of
 * the code rather than the code itself. Measured at one false positive across
 * 3,371 comment lines, and that one was a missing `\s` after the verb.
 */
const NARRATION_TAGS = [
  {
    tag: 'change-narration',
    // Anchored: these only mean anything at the start of a sentence.
    opening: [
      /^(?:added|updated|changed|modified|removed|refactored|fixed|renamed|moved|replaced|improved|introduced|switched|migrated|converted)\s/i,
      /^(?:this (?:is )?(?:now|was)|no longer|previously|we (?:now|used to))\b/i,
    ],
    patterns: [
      /\bas requested\b/i,
      /\bper (?:the )?(?:request|instructions)\b/i,
    ],
  },
  {
    tag: 'tutorial-voice',
    opening: [
      /^(?:now we|here we|first,? we|next,? we|then we|finally,? we|let'?s|we'?ll|you can (?:now|also)|notice that|as you can see)\b/i,
    ],
    patterns: [],
  },
  {
    tag: 'value-claim',
    opening: [],
    patterns: [
      /\bfor better (?:performance|readability|maintainability)\b/i,
      /\bfor improved\b/i,
      /\bto ensure (?:type safety|consistency)\b/i,
      /\bbest practice\b/i,
      /\bproduction[- ]ready\b/i,
      /\brobustness\b/i,
      /\bcomprehensive\b/i,
      /\bgracefully handle\b/i,
    ],
  },
  {
    tag: 'placeholder-deferral',
    opening: [],
    patterns: [
      /\bin a real (?:app|application|implementation|system|world)\b/i,
      /\bfor now,/i,
      /\bplaceholder\b/i,
      /\bmock(?:ed)? (?:data|implementation)\b/i,
      /\bimplement(?: this)? later\b/i,
      /\byou (?:would|should|may) want to\b/i,
      /\breplace (?:this )?with (?:your|a real)\b/i,
    ],
  },
] as const

interface RedundantHit {
  line: number
  comment: string
  code: string
}

interface NarrationHit {
  line: number
  comment: string
  tag: string
}

interface FileMeasurement {
  path: string
  ratio: number
  commentLines: number
  codeLines: number
  redundant: RedundantHit[]
  narration: NarrationHit[]
}

function excluded(path: string, content: string): boolean {
  if (!commentSyntaxFor(path)) return true
  if (SCAFFOLD_PATH.some((pattern) => pattern.test(path))) return true
  if (GENERATED_DECLARATION.test(content.split('\n', GENERATED_WINDOW).join('\n'))) return true
  return LICENCE_HEADER.test(content.slice(0, LICENCE_WINDOW_BYTES))
}

function truncate(value: string, limit: number): string {
  return value.length <= limit ? value : `${value.slice(0, limit - 1)}…`
}

function nextCodeLine(lines: ClassifiedLine[], from: number): ClassifiedLine | null {
  for (let i = from; i < lines.length; i++) {
    if (lines[i].kind === 'blank') continue
    return lines[i].kind === 'code' ? lines[i] : null
  }
  return null
}

/**
 * A single-line comment whose words are already on the statement below it.
 *
 * The comment must stand alone: a run of `//` lines is one wrapped paragraph,
 * and its last line is a sentence fragment. Comparing a fragment against the
 * code below it measures nothing — measured on this codebase, the only
 * restatement candidate outside a dispatch table was the tail of a three-line
 * comment explaining a transaction. The rule already refuses to look past a
 * following comment line; this is the same test on the other side.
 */
function redundantHit(lines: ClassifiedLine[], raw: string[], i: number): RedundantHit | null {
  const line = lines[i]
  if (line.kind !== 'line') return null
  const above = lines[i - 1]
  if (above && above.kind !== 'code' && above.kind !== 'blank') return null
  const text = line.text
  if (!text || text.length > MAX_COMMENT_CHARS) return null
  if (DIRECTIVE.test(text) || BANNER.test(text)) return null
  if (EXPLANATORY.test(text)) return null

  const below = nextCodeLine(lines, i + 1)
  if (!below || DECLARATION.test(below.code)) return null

  const commentWords = contentWords(text)
  if (commentWords.size < 2) return null
  const codeWords = contentWords(below.code)
  let shared = 0
  for (const word of commentWords) if (codeWords.has(word)) shared++
  if (shared / commentWords.size < OVERLAP_RATIO) return null

  const identifierWords = contentWords(withoutLiterals(below.code))
  if (![...commentWords].some((word) => identifierWords.has(word))) return null

  return { line: i + 1, comment: raw[i].trim(), code: below.code }
}

/**
 * Whether a comment line begins a sentence rather than continuing a wrapped
 * one. Without this, the wrapped second line of "…this turn's own task text and
 * / changed files did." reads as a change-narration comment starting with
 * "changed". Measured on this codebase: five such continuations, no real hits.
 */
function opensSentence(lines: ClassifiedLine[], index: number): boolean {
  const previous = lines[index - 1]
  if (!previous || previous.kind === 'code' || previous.kind === 'blank') return true
  return previous.text.length === 0 || /[.!?:]$/.test(previous.text)
}

function narrationHit(lines: ClassifiedLine[], raw: string, index: number): NarrationHit | null {
  const line = lines[index]
  if (line.kind === 'code' || line.kind === 'blank') return null
  const text = line.text
  if (!text || DIRECTIVE.test(text)) return null
  const sentenceStart = opensSentence(lines, index)
  for (const family of NARRATION_TAGS) {
    const matched = family.patterns.some((pattern) => pattern.test(text))
      || (sentenceStart && family.opening.some((pattern) => pattern.test(text)))
    if (matched) return { line: index + 1, comment: raw.trim(), tag: family.tag }
  }
  return null
}

function measure(path: string, content: string): FileMeasurement | null {
  const lines = classifyLines(path, content)
  if (lines.length === 0) return null
  const raw = content.split('\n')
  const dataBlocks = dataBlockIds(lines)

  let commentLines = 0
  let codeLines = 0
  for (const line of lines) {
    if (line.kind === 'blank') continue
    if (line.kind === 'code') codeLines++
    else if (!dataBlocks.has(line.block)) commentLines++
  }
  if (codeLines < MIN_CODE_LINES) return null

  const redundant: RedundantHit[] = []
  const narration: NarrationHit[] = []
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].block !== -1 && dataBlocks.has(lines[i].block)) continue
    const restating = redundantHit(lines, raw, i)
    if (restating) redundant.push(restating)
    const narrating = narrationHit(lines, raw[i], i)
    if (narrating) narration.push(narrating)
  }

  return { path, ratio: commentLines / codeLines, commentLines, codeLines, redundant, narration }
}

function median(values: number[]): number {
  if (values.length === 0) return 0
  const sorted = [...values].sort((left, right) => left - right)
  const middle = Math.floor(sorted.length / 2)
  return sorted.length % 2 === 0 ? (sorted[middle - 1] + sorted[middle]) / 2 : sorted[middle]
}

function percentile(values: number[], fraction: number): number {
  if (values.length === 0) return 0
  const sorted = [...values].sort((left, right) => left - right)
  return sorted[Math.min(sorted.length - 1, Math.floor(sorted.length * fraction))]
}

function round(value: number): number {
  return Math.round(value * 1000) / 1000
}

/**
 * Comment shape, measured against the repository's own baseline.
 *
 * The name is deliberate: this pass measures a property of the comments. It
 * never asserts who or what wrote them, because that is not provable from the
 * text, and a signed receipt may not claim more than it measured.
 *
 * Comment DENSITY is a metric here and never a finding. Measured across eight
 * repositories, the most densely commented codebase produced zero redundant
 * comments while the sparsest produced sixty-one: density and restatement are
 * close to anti-correlated, so a density rule would penalise exactly the
 * codebases worth rewarding.
 */
export const commentSlopAnalyzer: Analyzer = {
  id: 'comment-slop',
  name: 'Comment Signal',
  description:
    "Compares each file's commenting against this repository's own baseline and "
    + 'flags comments that restate the code or narrate the edit rather than explain it.',
  async run(index) {
    const candidates = index.files.filter(
      (file) =>
        file.content
        && (file.kind === 'source' || file.kind === 'component' || file.kind === 'route')
        && !excluded(file.path, file.content),
    )

    const candidateLimit = 2000
    const measurements: FileMeasurement[] = []
    for (const file of candidates.slice(0, candidateLimit)) {
      const measurement = measure(file.path, file.content!)
      if (measurement) measurements.push(measurement)
    }

    const ratios = measurements.map((item) => item.ratio)
    const ratioMedian = median(ratios)
    const densityThreshold = Math.max(DENSITY_MULTIPLE * ratioMedian, DENSITY_FLOOR)
    const isDensityOutlier = (item: FileMeasurement) =>
      item.ratio >= densityThreshold && item.commentLines >= DENSITY_MIN_COMMENTS

    const restating = measurements
      .filter((item) => item.redundant.length >= REDUNDANT_FILE_THRESHOLD)
      .sort((left, right) => right.redundant.length - left.redundant.length)
    const narrating = measurements
      .filter((item) => item.narration.length >= NARRATION_FILE_THRESHOLD)
      .sort((left, right) => right.narration.length - left.narration.length)

    const findingLimit = 10
    // Built for every matching file, then split by the cap into reported and
    // withheld. A finding that is never constructed cannot be compared against
    // another run, and the delta then reads it as introduced the first time a
    // cap slot frees up — see `analyzerWithheld` in types.ts.
    const restatingFindings: AnalyzerFinding[] = restating.map((item) => {
      const outlier = isDensityOutlier(item)
      const low = item.redundant.length >= REDUNDANT_LOW_THRESHOLD && outlier
      const sample = item.redundant[0]
      return {
        category: 'DOCUMENTATION',
        severity: low ? 'LOW' : 'INFO',
        title: `${item.redundant.length} comments restate the code in ${item.path}`,
        description:
          `${item.redundant.length} single-line comments in ${item.path} repeat words that already appear on the line `
          + `beneath them — for example line ${sample.line}, "${truncate(sample.comment, 80)}" above `
          + `${truncate(sample.code, 80)}. This file comments at ${round(item.ratio)} lines per code line against a `
          + `repository median of ${round(ratioMedian)}.`
          + (outlier ? " It is also a comment-density outlier against this repository's own baseline." : '')
          + ' Comments that restate the statement below them go stale silently, because nothing fails when the code'
          + ' changes and the comment does not.',
        filePath: item.path,
        line: sample.line,
        suggestion: 'Keep the comments that say why; delete the ones that repeat what.',
        impactScore: low ? 25 : 15,
        effort: 'low',
        metadata: { count: item.redundant.length, sample: item.redundant.slice(0, 5) },
      }
    })

    const narratingFindings: AnalyzerFinding[] = narrating.map((item) => {
      const low = item.narration.length >= NARRATION_LOW_THRESHOLD
      const sample = item.narration[0]
      const others = item.narration.length - 1
      const allPlaceholder = item.narration.every((hit) => hit.tag === 'placeholder-deferral')
      return {
        category: 'DOCUMENTATION',
        severity: low ? 'LOW' : 'INFO',
        title: allPlaceholder
          ? `${item.narration.length} comments in ${item.path} describe unfinished work`
          : `${item.narration.length} comments in ${item.path} describe the edit, not the code`,
        description: allPlaceholder
          ? `${item.path} contains ${item.narration.length} comments that describe the implementation as provisional — `
            + `line ${sample.line}, "${truncate(sample.comment, 80)}"${others ? `, and ${others} other${others > 1 ? 's' : ''}` : ''}. `
            + 'Unlike a TODO marker, these are invisible to the TODO tracker and to any grep for deferred work.'
          : `${item.narration.length} comments in ${item.path} narrate a change or address the reader rather than `
            + `document behaviour — line ${sample.line}, "${truncate(sample.comment, 80)}"`
            + `${others ? `, and ${others} other${others > 1 ? 's' : ''}` : ''}. `
            + 'Version control already records what changed; a comment that describes an edit is wrong the moment the'
            + ' next edit lands.',
        filePath: item.path,
        line: sample.line,
        suggestion: allPlaceholder
          ? 'Finish the work or mark it with a TODO so the deferred-work tracker can see it.'
          : 'Move change rationale to the commit message and keep the comment describing what the code does now.',
        impactScore: low ? 25 : 15,
        effort: 'low',
        metadata: { count: item.narration.length, sample: item.narration.slice(0, 5) },
      }
    })

    const findings = [
      ...restatingFindings.slice(0, findingLimit),
      ...narratingFindings.slice(0, findingLimit),
    ]
    const withheld = [
      ...restatingFindings.slice(findingLimit),
      ...narratingFindings.slice(findingLimit),
    ]

    const metrics = {
      eligibleFiles: measurements.length,
      commentRatioMedian: round(ratioMedian),
      commentRatioP90: round(percentile(ratios, 0.9)),
      densityOutlierFiles: measurements.filter(isDensityOutlier).length,
      redundantComments: measurements.reduce((total, item) => total + item.redundant.length, 0),
      redundantCommentFiles: restating.length,
      narrationComments: measurements.reduce((total, item) => total + item.narration.length, 0),
      narrationCommentFiles: narrating.length,
    }

    // Only the candidate-file cap is real coverage loss. The per-rule finding
    // cap bounds output over an analysis that still measured every candidate.
    if (candidates.length > candidateLimit) {
      return incompleteAnalyzerOutput(findings, {
        truncated: true,
        // The filter ran over the whole tree before the slice, so the files the
        // bound cut are counted, not merely unknown.
        coverageRatio: measuredCoverage(candidateLimit, candidates.length),
        detail: `Comment analysis measured ${candidateLimit} of ${candidates.length} candidate files.`,
        metrics: { ...metrics, candidates: candidates.length, candidateLimit },
      }, withheld)
    }
    if (restating.length > findingLimit || narrating.length > findingLimit) {
      return annotatedAnalyzerOutput(findings, {
        detail: `Comment output capped at ${findingLimit} files per rule (${restating.length} restating, ${narrating.length} narrating).`,
        metrics: { ...metrics, candidates: candidates.length, candidateLimit },
      }, withheld)
    }
    return annotatedAnalyzerOutput(findings, {
      metrics: { ...metrics, candidates: candidates.length, candidateLimit },
    })
  },
}
