import { classifyLines } from './comments'
import type { Analyzer, AnalyzerFinding, IndexedFile } from './types'
import { looksGenerated } from './support'

const HUGE_LOC = 800
const LARGE_ASSET_BYTES = 5 * 1024 * 1024

/**
 * Lines of CODE — comments and blanks excluded.
 *
 * `IndexedFile.loc` counts non-blank lines, so a heavily documented file
 * measures larger than it is, and this analyzer QUOTES its number in a paid
 * deliverable: "parser.ts has 2202 lines of code" is disproved by the reader's
 * own `wc`, and the same overcount pushes files across the HIGH threshold that
 * are only oversized in prose. Measuring with the classifier this engine already
 * ships costs nothing in recall — a file with 800 lines of code has 800 lines of
 * code however it is counted — and it is what makes the sentence true.
 *
 * Falls back to `loc` when the file has no classifier or no readable content:
 * an approximate number is better than dropping the finding, and `loc` bounds
 * the code count from above, so the fallback can only under-report.
 */
function codeLoc(file: IndexedFile): number {
  if (!file.content) return file.loc
  const classified = classifyLines(file.path, file.content)
  if (classified.length === 0) return file.loc
  return classified.filter((line) => line.kind === 'code').length
}

/** Flags unmaintainably large source files and oversized committed assets. */
export const sizeAnalyzer: Analyzer = {
  id: 'size',
  name: 'File Size',
  description: 'Detects oversized source files and large binary assets committed to the repo.',
  async run(index) {
    const findings: AnalyzerFinding[] = []

    for (const f of index.files) {
      // `loc` bounds the code count from above, so it decides cheaply which
      // files are worth classifying; the classified count then decides.
      if (f.loc > HUGE_LOC && (f.kind === 'source' || f.kind === 'component' || f.kind === 'route')) {
        const loc = codeLoc(f)
        if (loc <= HUGE_LOC) continue
        if (f.content && looksGenerated(f.content)) {
          // Machine-written files don't get hand-refactoring advice — the
          // actionable observation is that a build artifact is committed.
          findings.push({
            category: 'STRUCTURE',
            severity: 'LOW',
            title: `Generated artifact committed: ${f.path.split('/').pop()} (${loc} LOC)`,
            description: `${f.path} declares itself autogenerated. Large generated files bloat diffs and invite accidental hand-edits.`,
            filePath: f.path,
            suggestion: 'Generate it at build time instead of committing it, or mark it linguist-generated in .gitattributes.',
            impactScore: 25,
            effort: 'low',
            metadata: { loc, generated: true },
          })
          continue
        }
        findings.push({
          category: 'TECH_DEBT',
          severity: loc > 2000 ? 'HIGH' : 'MEDIUM',
          title: `Oversized file: ${f.path.split('/').pop()} (${loc} LOC)`,
          description: `${f.path} has ${loc} lines of code. Files this large are hard to review, test, and safely change.`,
          filePath: f.path,
          suggestion: 'Split into focused modules along responsibility boundaries.',
          impactScore: Math.min(90, 40 + Math.floor(loc / 100)),
          effort: 'medium',
          metadata: { loc },
        })
      }
      if (f.kind === 'asset' && f.sizeBytes > LARGE_ASSET_BYTES) {
        findings.push({
          category: 'STRUCTURE',
          severity: 'LOW',
          title: `Large asset committed: ${f.path.split('/').pop()}`,
          description: `${f.path} is ${(f.sizeBytes / 1024 / 1024).toFixed(1)} MB. Large binaries bloat clones and slow CI.`,
          filePath: f.path,
          suggestion: 'Move large assets to object storage or Git LFS.',
          impactScore: 25,
          effort: 'low',
        })
      }
    }
    return findings
  },
}
