/** Shared constants required by deterministic analyzers. */
export const SUPPORTED_TREESITTER_LANGS: readonly string[] = ['c#', 'go', 'java', 'rust', 'php', 'ruby']
export const SAST_COVERED_LANGUAGES: ReadonlySet<string> = new Set(['TypeScript', 'JavaScript', 'Python'])
export function looksGenerated(content: string): boolean {
  const head = content.split('\n', 5).join('\n')
  return /auto-?generated|@generated|generated by|do not edit/i.test(head)
}

/**
 * Blank out quoted string literals so a brace, slash or keyword inside one is
 * not read as code. Shared by every parser-free analyzer that needs it.
 *
 * The `[^\\]` in the second branch is load-bearing and is why this lives in one
 * place. The obvious spelling — `(?:\\.|(?!\1).)*` — lets a backslash be
 * consumed by EITHER branch, so an unterminated literal makes the engine try
 * every partition of the backslashes in it: 2^n. A commented-out email regex in
 * zod (`packages/zod/src/v3/types.ts:607`, 133 backslashes, no closing quote)
 * turned one 928-character line into a scan that ran past seven minutes at 100%
 * CPU and never finished — outliving both the 5s-per-file and 5min-per-pass
 * ceilings, because those bound the SAST pass and this runs in the registry
 * analyzers. Excluding the backslash from the second branch makes the two
 * disjoint, so each character has exactly one way to match and the same line
 * completes in under a millisecond with identical output.
 *
 * A fresh literal per call rather than a shared `/g` constant: a global regex
 * carries `lastIndex`, and one shared between call sites is a stateful bug
 * waiting for the first caller that uses it with anything but `replace`.
 */
export function stripStringLiterals(code: string, replacement: string): string {
  return code.replace(/(["'`])(?:\\.|(?!\1)[^\\])*\1/g, replacement)
}
